# tasks file
---
- name: Remove myapp
  ansible.builtin.file:
    path: "~{{ username }}/myapp"
    state: absent

- name: Create ~/myapp directory
  ansible.builtin.file:
    path: ~{{ username }}/myapp
    state: directory
    mode: '0755'

- name: Ensure ~/.local exists
  file:
    path: "{{ ansible_env.HOME }}/.local"
    state: directory
    mode: '0755'

- name: Run task only on x86_64 or amd64
  ansible.builtin.debug:
    msg: "This host is x86_64 or amd64"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Remove ~/.local/bin/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/bin/"
    state: absent

- name: Remove ~/.local/lib/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/lib/"
    state: absent

- name: Remove ~/.local/share/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/share/"
    state: absent

- name: Remove ~/.local/state/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/state/"
    state: absent

- name: create ~/.local/bin/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/bin/"
    state: directory
    mode: '0755'

- name: create ~/.local/lib/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/lib/"
    state: directory
    mode: '0755'

- name: create ~/.local/share/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/share/"
    state: directory
    mode: '0755'

- name: create ~/.local/state/ files
  ansible.builtin.file:
    path: "~{{ username }}/.local/state/"
    state: directory
    mode: '0755'

- name: Download tarballs with custom peco
  ansible.builtin.get_url:
    url: "https://github.com/peco/peco/releases/download/v0.5.11/peco_linux_amd64.tar.gz"
    dest: "~{{ username }}/myapp/peco_linux_amd64.tar.gz"
    mode: '0644'
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Extract tarballs peco
  become: false
  become_user: "{{ username }}"
  unarchive:
    src: "~{{ username }}/myapp/peco_linux_amd64.tar.gz"
    dest: "~{{ username }}/myapp"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Copy bin file to ~/.local/bin peco
  become: false
  become_user: "{{ username }}"
  copy:
    src: "~{{ username }}/myapp/peco_linux_amd64/peco"
    dest: "~{{ username }}/.local/bin/"
    remote_src: yes
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Download tarballs with custom names
  ansible.builtin.get_url:
    url: "{{ item.url }}/{{ item.version }}/{{ item.name }}-{{ item.version }}-{{ item.arch }}-{{ item.target }}.{{ item.extension }}"
    dest: "~{{ username }}/myapp/{{ item.name }}-{{ item.version }}-{{ item.arch }}-{{ item.target }}.{{ item.extension }}"
    mode: '0644'
  loop: "{{ tarballs_dir }}"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Extract tarballs
  become: false
  become_user: "{{ username }}"
  unarchive:
    src: "~{{ username }}/myapp/{{ item.name }}-{{ item.version }}-{{ item.arch }}-{{ item.target }}.{{ item.extension }}"
    dest: "~{{ username }}/myapp"
  loop: "{{ tarballs_dir }}"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Copy bin file to ~/.local/bin
  become: false
  become_user: "{{ username }}"
  copy:
    src: "~{{ username }}/myapp/{{ item.name }}-{{ item.version }}-{{ item.arch }}-{{ item.target }}/{{ item.file }}"
    dest: "~{{ username }}/.local/bin/"
    remote_src: yes
  loop: "{{ tarballs_dir }}"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Make file in ~/.local/bin/ executable
  become: false
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "~{{ username }}/.local/bin/{{ item.file }}"
    mode: '0755'
    state: file
  loop: "{{ tarballs_dir }}"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Download tarballs with custom names
  ansible.builtin.get_url:
    url: "{{ item.url }}/{{ item.version }}/{{ item.name }}.{{ item.extension }}"
    dest: "~{{ username }}/myapp/{{ item.name }}.{{ item.extension }}"
    mode: '0644'
  loop: "{{ tarballs_file }}"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Extract tarballs
  become: false
  become_user: "{{ username }}"
  unarchive:
    src: "~{{ username }}/myapp/{{ item.name }}.{{ item.extension }}"
    dest: "~{{ username }}/myapp"
  loop: "{{ tarballs_file }}"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Copy bin file to ~/.local/bin
  become: false
  become_user: "{{ username }}"
  copy:
    src: "~{{ username }}/myapp/{{ item.file }}"
    dest: "~{{ username }}/.local/bin/"
    remote_src: yes
  loop: "{{ tarballs_file }}"
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Make file in ~/.local/bin/ executable
  become: false
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "~{{ username }}/.local/bin/{{ item.file }}"
    mode: '0755'
    state: file
  loop: "{{ tarballs_file }}"

- name: Ensure build dependencies are present
  become: false
  become_user: "{{ username }}"
  package:
    name:
      - build-essential  # for Debian/Ubuntu
      - gcc
      - make
      - git
    state: present
  when: ansible_os_family == "Debian"

- name: Clone the repository from Git fzy
  become: false
  become_user: "{{ username }}"
  git:
    repo: "{{ fzy_source_package_url | default('https://github.com/jhawthorn/fzy.git') }}"
    dest: "~{{ username }}/myapp/fzy"
    version: "{{ fzy_source_repo_branch | default('master') }}"
    force: yes

- name: Compile and install from source fzy
  become: false
  become_user: "{{ username }}"
  args:
    chdir: "~{{ username }}/myapp/fzy"
  shell: |
    make

- name: Copy bin file to ~/.local/bin fzy
  become: false
  become_user: "{{ username }}"
  copy:
    src: "~{{ username }}/myapp/fzy/fzy"
    dest: "~{{ username }}/.local/bin/"
    remote_src: yes

- name: Download tarballs neovim locals with custom names
  ansible.builtin.get_url:
    url: "{{ nvim_url }}/{{ nvim_version }}/{{ nvim_name }}.{{ nvim_extension }}"
    dest: "~{{ username }}/myapp/{{ nvim_name }}.{{ nvim_extension }}"
    mode: '0644'
  when: ansible_architecture in ['x86_64', 'amd64']

- name: Extract tarballs neovim
  become: false
  become_user: "{{ username }}"
  unarchive:
    src: "~{{ username }}/myapp/{{ nvim_name }}.{{ nvim_extension }}"
    dest: "~{{ username }}/myapp"

- name: Copy bin file to ~/.local/bin for neovim
  become: false
  become_user: "{{ username }}"
  copy:
    src: "~{{ username }}/myapp/{{ nvim_name }}/bin"
    dest: "~{{ username }}/.local/"
    remote_src: yes

- name: Copy bin file to ~/.local/lib for neovim
  become: false
  become_user: "{{ username }}"
  copy:
    src: "~{{ username }}/myapp/{{ nvim_name }}/lib"
    dest: "~{{ username }}/.local/"
    remote_src: yes

- name: Copy bin file to ~/.local/share for neovim
  become: false
  become_user: "{{ username }}"
  copy:
    src: "~{{ username }}/myapp/{{ nvim_name }}/share"
    dest: "~{{ username }}/.local/"
    remote_src: yes

- name: Create nvim directory
  become: false
  become_user: "{{ username }}"
  ansible.builtin.copy:
    src: nvim
    dest: "~{{ username }}/.config/"
    mode: '0644'

- name: Install glab
  snap:
    name: glab
    classic: yes
  when: ansible_facts['os_family'] == "Debian"

- name: set default shell for users
  user:
    name: '{{ username }}'
    shell: /bin/zsh

- name: Create fonts directory
  become: true
  become_user: "{{ username }}"
  file:
    path: "~{{ username }}/.fonts"
    mode: '0755'
    state: directory
- name: Copy powerlevel10k recommanded fonts
  become: true
  become_user: "{{ username }}"
  copy:
    src: "fonts/{{ item }}"
    dest: "~{{ username }}/.fonts/{{ item }}"
    mode: '0644'
  loop:
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf
- name: ensure fonts directory
  become: true
  become_user: "{{ username }}"
  file:
    path: "{{ fonts_path }}"
    state: directory
- name: clone oh-my-zsh for user
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: true
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "~{{ username }}/.oh-my-zsh"
- name: clone powerlevel10k for users
  become: true
  become_user: "{{ username }}"
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    version: master
    dest: "~{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
- name: clone zsh-autosuggestions for users
  become: true
  become_user: "{{ username }}"
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    version: master
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
- name: clone forgit for users
  become: true
  become_user: "{{ username }}"
  git:
    repo: 'https://github.com/wfxr/forgit.git'
    version: 755b3dd9f85c044a3bd76059b24b1ad63d5c0617
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/forgit'
- name: clone syntax highlighting  for users
  become: true
  become_user: "{{ username }}"
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    version: master
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'

- name: clone enhancd for users
  become_user: "{{ username }}"
  git:
    repo: 'https://github.com/babarot/enhancd.git'
    version: main
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/enhancd'
- name: write .p10k.zsh for users
  become: true
  become_user: "{{ username }}"
  template:
    src: p10k.zsh.j2
    dest: ~{{ username }}/.p10k.zsh
    backup: yes
    mode: 'u=rw,go=r'
- name: write .zshrc for user
  become: true
  become_user: "{{ username }}"
  template:
    src: zshrc.j2
    dest: "~{{ username }}/.zshrc"
    backup: yes
    mode: "u=rw,go=r"
- name: write .alias_fzf for user
  become: true
  become_user: "{{ username }}"
  template:
    src: alias_fzf.j2
    dest: "~{{ username }}/.alias_fzf"
    backup: yes
    mode: "u=rw,go=r"
- name: write .alias_git for user
  become: true
  become_user: "{{ username }}"
  template:
    src: alias_git.j2
    dest: "~{{ username }}/.alias_git"
    backup: yes
    mode: "u=rw,go=r"
- name: write .alias_lab for user
  become_user: "{{ username }}"
  template:
    src: alias_lab.j2
    dest: "~{{ username }}/.alias_lab"
    backup: yes
    mode: "u=rw,go=r"
- name: write .alias_tmux for user
  become_user: "{{ username }}"
  template:
    src: alias_tmux.j2
    dest: "~{{ username }}/.alias_tmux"
    backup: yes
    mode: "u=rw,go=r"
- name: write .alias_utility for user
  become: true
  become_user: "{{ username }}"
  template:
    src: alias_utility.j2
    dest: "~{{ username }}/.alias_utility"
    backup: yes
    mode: "u=rw,go=r"
- name: write .alias_yabt for user
  become: true
  become_user: "{{ username }}"
  template:
    src: alias_yabt.j2
    dest: "~{{ username }}/.alias_yabt"
    backup: yes
    mode: "u=rw,go=r"
- name: Clone TPM repository
  become: true
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "~{{ username }}/.tmux/plugins/tpm"
- name: write .tmux.conf for user
  become: true
  become_user: "{{ username }}"
  template:
    src: tmux.conf.j2
    dest: "~{{ username }}/.tmux.conf"
    backup: yes
    mode: "u=rw,go=rw"
- name: Ensure curl is installed
  package:
    name: curl
    state: present
- name: Install NVM
  shell: "curl -o- {{ nvm_install_url }} | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm"
- name: Load NVM environment
  shell: 'echo ". $HOME/.nvm/nvm.sh" >> ~/.bashrc && . $HOME/.nvm/nvm.sh'
  args:
    executable: /bin/bash
- name: Install Node.js using NVM
  shell: ". $HOME/.nvm/nvm.sh && nvm install {{ node_version }}"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}"
- name: Verify Node.js version
  shell: ". $HOME/.nvm/nvm.sh && node -v"
  args:
    executable: /bin/bash
  register: node_version_output
- name: Print Node.js version
  debug:
    msg: "Node.js version installed: {{ node_version_output.stdout }}"
- name: Verify current NVM version
  shell: ". $HOME/.nvm/nvm.sh && nvm current"
  args:
    executable: /bin/bash
  register: nvm_current_output
- name: Print current NVM-managed Node.js version
  debug:
    msg: "NVM current version: {{ nvm_current_output.stdout }}"
- name: Verify NPM version
  shell: ". $HOME/.nvm/nvm.sh && npm -v"
  args:
    executable: /bin/bash
  register: npm_version_output
- name: Print NPM version
  debug:
    msg: "NPM version: {{ npm_version_output.stdout }}"
- name: Set Git user name
  ansible.builtin.command: git config --global user.name "{{ git_user_name }}"
- name: Set Git user email
  ansible.builtin.command: git config --global user.email "{{ git_user_email }}"
- name: Set Git core editor
  ansible.builtin.command: git config --global core.editor "{{ git_core_editor }}"

- name: Remove myapp
  ansible.builtin.file:
    path: "~{{ username }}/myapp"
    state: absent

