# tasks file
---
- name: Remove myapp
  ansible.builtin.file:
    path: "~{{ username }}/myapp"
    state: absent

- name: Create ~/myapp directory
  ansible.builtin.file:
    path: ~{{ username }}/myapp
    state: directory
    mode: '0755'

- include_tasks: setup-local-dir.yml

- include_tasks: setup-zsh.yml

- include_tasks: setup-tmux.yml

- include_tasks: setup-neovim.yml

- include_tasks: setup-git.yml

- include_tasks: setup-nodejs.yml

- name: Remove myapp
  ansible.builtin.file:
    path: "~{{ username }}/myapp"
    state: absent