---
- name: clone oh-my-zsh for user
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: clone powerlevel10k for users
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: clone zsh-autosuggestions for users
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    version: master
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

- name: clone forgit for users
  git:
    repo: 'https://github.com/wfxr/forgit.git'
    version: 755b3dd9f85c044a3bd76059b24b1ad63d5c0617
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/forgit'

- name: clone syntax highlighting  for users
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    version: master
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'

- name: clone enhancd for users
  git:
    repo: 'https://github.com/babarot/enhancd.git'
    version: main
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/enhancd'

- name: write .p10k.zsh for users
  template:
    src: p10k.zsh.j2
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
    backup: yes
    mode: 'u=rw,go=r'

- name: write .zshrc for user
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    backup: yes
    mode: "u=rw,go=r"

- name: write .alias_fzf for user
  template:
    src: alias_fzf.j2
    dest: "{{ ansible_env.HOME }}/.alias_fzf"
    backup: yes
    mode: "u=rw,go=r"

- name: write .alias_git for user
  template:
    src: alias_git.j2
    dest: "{{ ansible_env.HOME }}/.alias_git"
    backup: yes
    mode: "u=rw,go=r"

- name: write .alias_lab for user
  template:
    src: alias_lab.j2
    dest: "{{ ansible_env.HOME }}/.alias_lab"
    backup: yes
    mode: "u=rw,go=r"

- name: write .alias_tmux for user
  template:
    src: alias_tmux.j2
    dest: "{{ ansible_env.HOME }}/.alias_tmux"
    backup: yes
    mode: "u=rw,go=r"

- name: write .alias_utility for user
  template:
    src: alias_utility.j2
    dest: "{{ ansible_env.HOME }}/.alias_utility"
    backup: yes
    mode: "u=rw,go=r"

- name: write .alias_yabt for user
  template:
    src: alias_yabt.j2
    dest: "{{ ansible_env.HOME }}/.alias_yabt"
    backup: yes
    mode: "u=rw,go=r"

