---
- name: Install Claude Code
  ansible.builtin.shell:
    cmd: curl -fsSL https://claude.ai/install.sh | bash
    executable: /bin/bash

- name: Install OpenCode
  ansible.builtin.shell:
    cmd: curl -fsSL https://opencode.ai/install | bash
    executable: /bin/bash

