---
- name: Select tarballs list based on architecture
  set_fact:
    tarballs_list: "{{ (ansible_architecture in ['x86_64', 'amd64'])
                       | ternary(tarballs_file, (ansible_architecture in ['arm64', 'aarch64'])
                       | ternary(tarballs_file_arm64, [])) }}"

- name: Download tarballs with custom names
  ansible.builtin.get_url:
    url: "{{ item.url }}/{{ item.version }}/{{ item.name }}_{{ item.arch }}.{{ item.extension }}"
    dest: "{{ ansible_env.HOME }}/myapp/{{ item.name }}.{{ item.extension }}"
    mode: '0644'
  loop: "{{ tarballs_list }}"

- name: Remove files with shell loop
  shell: rm {{ ansible_env.HOME }}/.local/bin/{{ item.file }}
  loop: "{{ tarballs_list }}"
  failed_when: false

- name: Ensure is removed
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/{{ item.file }}"
    state: absent
  loop: "{{ tarballs_list }}"

- name: Extract tarballs
  unarchive:
    src: "{{ ansible_env.HOME }}/myapp/{{ item.name }}.{{ item.extension }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
  loop: "{{ tarballs_list }}"

- name: Make file in ~/.local/bin/ executable
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin/{{ item.file }}"
    mode: '0755'
    state: file
  loop: "{{ tarballs_list }}"

