---
- name: Clone the repository from Git fzy
  git:
    repo: "https://github.com/dylanaraps/neofetch.git"
    dest: "{{ ansible_env.HOME }}/myapp/neofetch"
    version: "master"
    force: yes

- name: Ensure is removed
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/neofetch"
    state: absent

- name: Compile and install from source neofetch
  args:
    chdir: "{{ ansible_env.HOME }}/myapp/neofetch"
  shell: |
    make install PREFIX={{ ansible_env.HOME }}/.local

