---
- name: Remove all files
  shell: |
    rm -rf {{ ansible_env.HOME }}/.nvm
    rm -rf {{ ansible_env.HOME }}/.npm
    rm -rf {{ ansible_env.HOME }}/.local/bin/node
    rm -rf {{ ansible_env.HOME }}/.local/bin/npm
  failed_when: false

- name: Ensure is removed
  file:
    path: "{{ ansible_env.HOME }}/.nvm"
    state: absent

- name: Install from script
  shell: |
    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

- name: Check versions with different flags
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm --version"
  failed_when: false
