---
- name: Clone the repository from Git pfetch
  git:
    repo: "https://github.com/dylanaraps/pfetch.git"
    dest: "{{ ansible_env.HOME }}/myapp/pfetch"
    version: "master"
    force: yes

- name: Remove all pfetch files
  shell: rm -rf {{ ansible_env.HOME }}/pfetch
  failed_when: false

- name: Ensure is removed
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/pfetch"
    state: absent

- name: Compile and install from source pfetch ubuntu
  args:
    chdir: "{{ ansible_env.HOME }}/myapp/pfetch"
  shell: |
    make install PREFIX={{ ansible_env.HOME }}/.local
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install pfetch darwin
  shell: |
    cp pfetch {{ ansible_env.HOME }}/.local/bin/.
  args:
    chdir: "{{ ansible_env.HOME }}/myapp/pfetch"
  when: ansible_os_family == "Darwin"
