---
- name: Select nvim list based on architecture and Ubuntu version
  set_fact:
    nvim_list: >-
      {{ (
          ansible_architecture in ['x86_64', 'amd64'] and ansible_distribution_version is version('20.04', '==')
        ) | ternary(
          nvim_ubuntu_2004,
          (
            ansible_architecture in ['x86_64', 'amd64'] and ansible_distribution_version is version('24.04', '==')
          ) | ternary(
            nvim_ubuntu_2404,
            (
              ansible_architecture in ['arm64', 'aarch64'] and ansible_distribution_version is version('20.04', '==')
            ) | ternary(
              nvim_ubuntu_2004_arm64,
              (
                ansible_architecture in ['arm64', 'aarch64'] and ansible_distribution_version is version('24.04', '==')
              ) | ternary(
                nvim_ubuntu_2404_arm64,
                []
              )
            )
          )
        ) 
      }}

- name: Download tarballs neovim locals with custom names
  ansible.builtin.get_url:
    url: "{{ nvim_list.nvim_url }}/{{ nvim_list.nvim_version }}/{{ nvim_list.nvim_name }}.{{ nvim_list.nvim_extension }}"
    dest: "{{ ansible_env.HOME }}/myapp/neovim.{{ nvim_list.nvim_extension }}"
    mode: '0644'

- name: Extract tarballs neovim
  unarchive:
    src: "{{ ansible_env.HOME }}/myapp/neovim.tar.gz"
    dest: "{{ ansible_env.HOME }}/myapp"

- name: Remove all neovim files
  shell: |
    rm -rf {{ ansible_env.HOME }}/.config/nvim
    rm -rf {{ ansible_env.HOME }}/.local/bin/neovim
    rm -rf {{ ansible_env.HOME }}/.local/lib/neovim
    rm -rf {{ ansible_env.HOME }}/.local/share/neovim
  failed_when: false

- name: Ensure is removed from .config
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: absent

- name: Ensure is removed from bin
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/neovim"
    state: absent

- name: Ensure is removed from lib
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/lib/nvim"
    state: absent

- name: Ensure is removed from share
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim"
    state: absent

- name: Copy bin file to ~/.local/bin for neovim
  copy:
    src: "{{ ansible_env.HOME }}/myapp/{{ nvim_list.nvim_name }}/bin"
    dest: "{{ ansible_env.HOME }}/.local/"
    remote_src: yes

- name: Copy bin file to ~/.local/lib for neovim
  copy:
    src: "{{ ansible_env.HOME }}/myapp/{{ nvim_list.nvim_name }}/lib"
    dest: "{{ ansible_env.HOME }}/.local/"
    remote_src: yes

- name: Copy bin file to ~/.local/share for neovim
  copy:
    src: "{{ ansible_env.HOME }}/myapp/{{ nvim_list.nvim_name }}/share"
    dest: "{{ ansible_env.HOME }}/.local/"
    remote_src: yes

- name: Create nvim directory
  ansible.builtin.copy:
    src: nvim
    dest: "{{ ansible_env.HOME }}/.config/"
    mode: '0644'

- name: Make file in ~/.local/bin/ executable
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin/nvim"
    mode: '0755'
    state: file
