# tasks file
---
- name: Task for Ubuntu 20.04
  ansible.builtin.debug:
    msg: "Running on Ubuntu 20.04"
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "20.04"

- name: Task for Ubuntu 24.04
  ansible.builtin.debug:
    msg: "Running on Ubuntu 24.04"
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "24.04"

- name: Display OS facts
  debug:
    msg: |
      OS Family: {{ ansible_facts['os_family'] }}
      Distribution: {{ ansible_facts['distribution'] }}
      Distribution Version: {{ ansible_facts['distribution_version'] }}
      Distribution Release: {{ ansible_facts['distribution_release'] }}
      architectures: {{ ansible_architecture }}

- name: Remove myapp
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/myapp"
    state: absent

- name: Create ~/myapp directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/myapp"
    state: directory
    mode: '0755'

- include_tasks: setup-fonts.yml
- include_tasks: setup-zsh-starship.yml
- include_tasks: setup-peco.yaml
- include_tasks: setup-git.yml
- include_tasks: setup-tmux.yml

- include_tasks: install-pfetch.yml
- include_tasks: install-packages-tarball-dir.yml
- include_tasks: install-packages-fzy.yml
- include_tasks: install-npm.yml
- include_tasks: install-neovim.yml
  when: not (ansible_distribution == "Ubuntu"
             and ansible_distribution_version == "20.04"
             and ansible_architecture in ['arm64', 'aarch64'])

- name: Remove myapp
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/myapp"
    state: absent

