---
- name: Remove all zsh files
  shell: |
    rm -rf {{ ansible_facts['env'].HOME }}/.oh-my-zsh
    rm -rf {{ ansible_facts['env'].HOME }}/.p10k.zsh
    rm -rf {{ ansible_facts['env'].HOME }}/.zshrc
    rm -rf {{ ansible_facts['env'].HOME }}/.alias_fzf
    rm -rf {{ ansible_facts['env'].HOME }}/.alias_git
    rm -rf {{ ansible_facts['env'].HOME }}/.alias_forgit
    rm -rf {{ ansible_facts['env'].HOME }}/.alias_lab
    rm -rf {{ ansible_facts['env'].HOME }}/.alias_tmux
    rm -rf {{ ansible_facts['env'].HOME }}/.alias_utility
    rm -rf {{ ansible_facts['env'].HOME }}/.alias_yab
  failed_when: false

- name: clone oh-my-zsh for user
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ ansible_facts['env'].HOME }}/.oh-my-zsh"

- name: clone powerlevel10k for users
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    version: master
    dest: "{{ ansible_facts['env'].HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: clone zsh-autosuggestions for users
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    version: master
    dest: '{{ ansible_facts["env"].HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

- name: clone forgit for users
  git:
    repo: 'https://github.com/wfxr/forgit.git'
    version: 755b3dd9f85c044a3bd76059b24b1ad63d5c0617
    dest: '{{ ansible_facts["env"].HOME }}/.oh-my-zsh/custom/plugins/forgit'

- name: clone syntax highlighting  for users
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    version: master
    dest: '{{ ansible_facts["env"].HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'

- name: clone enhancd for users
  git:
    repo: 'https://github.com/babarot/enhancd.git'
    version: main
    dest: '{{ ansible_facts["env"].HOME }}/.oh-my-zsh/custom/plugins/enhancd'

- name: write .p10k.zsh for users
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_facts['env'].HOME }}/.{{ item }}"
    backup: yes
    mode: 'u=rw,go=r'
  loop:
    - p10k.zsh
    - zshrc
    - alias_fzf
    # - alias_git
    - alias_forgit
    - alias_lab
    - alias_tmux
    - alias_utility
    - alias_yabt

