---
- name: Set Git user name
  ansible.builtin.command: git config --global user.name "{{ git_user_name }}"

- name: Set Git user email
  ansible.builtin.command: git config --global user.email "{{ git_user_email }}"

- name: Set Git core editor
  ansible.builtin.command: git config --global core.editor "{{ git_core_editor }}"

- name: Set Git signed commit
  ansible.builtin.command: git config --global gpg.format ssh

- name: Set Git signed commit ssh pub key
  ansible.builtin.command: git config --global user.signingkey "{{ git_pub_key }}"

- name: Set Git signed always
  ansible.builtin.command: git config --global commit.gpgsign true

