---
- name: Remove all zsh files
  shell: |
    rm -rf {{ ansible_env.HOME }}/.oh-my-zsh
    rm -rf {{ ansible_env.HOME }}/.p10k.zsh
    rm -rf {{ ansible_env.HOME }}/.config/starship.toml
    rm -rf {{ ansible_env.HOME }}/.zshrc
    rm -rf {{ ansible_env.HOME }}/.alias_fzf
    rm -rf {{ ansible_env.HOME }}/.alias_git
    rm -rf {{ ansible_env.HOME }}/.alias_forgit
    rm -rf {{ ansible_env.HOME }}/.alias_lab
    rm -rf {{ ansible_env.HOME }}/.alias_tmux
    rm -rf {{ ansible_env.HOME }}/.alias_utility
    rm -rf {{ ansible_env.HOME }}/.alias_yab
    ls -la {{ ansible_env.HOME }}
  failed_when: false

- name: clone oh-my-zsh for user
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: clone zsh-autosuggestions for users
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    version: master
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

- name: clone forgit for users
  git:
    repo: 'https://github.com/wfxr/forgit.git'
    version: 755b3dd9f85c044a3bd76059b24b1ad63d5c0617
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/forgit'

- name: clone syntax highlighting  for users
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    version: master
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'

- name: clone enhancd for users
  git:
    repo: 'https://github.com/babarot/enhancd.git'
    version: main
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/enhancd'

- name: copy alias
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    backup: yes
    mode: 'u=rw,go=r'
  loop:
    - alias_fzf
    - alias_forgit
    - alias_lab
    - alias_tmux
    - alias_utility
    - alias_yabt

- name: copy zsh with starship
  template:
    src: "zshrc-starship.j2"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    backup: yes
    mode: 'u=rw,go=r'

- name: copy config starship file
  template:
    src: "starship.j2"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    backup: yes
    mode: 'u=rw,go=r'

- name: Download starship x86
  get_url:
    url: "{{ starship.url }}/{{ starship.version }}/{{ starship.name }}-x86_64-{{ starship.compiler }}.{{ starship.extension }}"
    dest: "{{ ansible_env.HOME }}/myapp/"
    mode: '0644'
  when: 
  - ansible_facts['distribution'] == "Ubuntu"
  - ansible_facts['architecture'] in ['x86_64', 'amd64']

- name: Download starship arm64
  get_url:
    url: "{{ starship.url }}/{{ starship.version }}/{{ starship.name }}-aarch64-{{ starship.compiler }}.{{ starship.extension }}"
    dest: "{{ ansible_env.HOME }}/myapp/"
    mode: '0644'
  when: 
  - ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Fedora"
  - ansible_facts['architecture'] in ['aarch64', 'arm64', 'armv8l']

- name: Download starship darwin
  get_url:
    url: "{{ starship_darwin.url }}/{{ starship_darwin.version }}/{{ starship_darwin.name }}-{{ starship_darwin.compiler }}.{{ starship_darwin.extension }}"
    dest: "{{ ansible_env.HOME }}/myapp/"
    mode: '0644'
  when: ansible_facts['os_family'] == "Darwin"

- name: Compile and install from source pfetch ubuntu
  shell: |
    ls -la {{ ansible_env.HOME }}/myapp/

- name: Remove files with shell loop
  shell: rm {{ ansible_env.HOME }}/.local/bin/{{ starship.name }}
  failed_when: false

- name: Ensure is removed
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/{{ starship.name }}"
    state: absent

- name: Extract tarballs x86
  unarchive:
    src: "{{ ansible_env.HOME }}/myapp/{{ starship.name }}-x86_64-{{ starship.compiler }}.{{ starship.extension }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
  when: 
  - ansible_facts['distribution'] == "Ubuntu"
  - ansible_facts['architecture'] in ['x86_64', 'amd64']

- name: Extract tarballs arm64
  unarchive:
    src: "{{ ansible_env.HOME }}/myapp/{{ starship.name }}-aarch64-{{ starship.compiler }}.{{ starship.extension }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
  when: 
  - ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Fedora"
  - ansible_facts['architecture'] in ['aarch64', 'arm64', 'armv8l']

- name: Extract tarballs darwin
  unarchive:
    src: "{{ ansible_env.HOME }}/myapp/{{ starship_darwin.name }}-{{ starship_darwin.compiler }}.{{ starship_darwin.extension }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
  when: ansible_facts['os_family'] == "Darwin"

- name: Make file in ~/.local/bin/ executable
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin/{{ starship.name }}"
    mode: '0755'
    state: file