# defaults file
---

# defaults file for ansible-role-p10k

# Powerlevel10k Git repository url
p10k_repository_url: 'https://github.com/romkatv/powerlevel10k.git'

# Install p10k for the following linux users
# Default: the linux user running Ansible
p10k_users:
  - "{{ ansible_facts['user_id'] }}"

# Zsh plugin used, zsh, ohmyzsh, prezto, Zim, etc..
# All plugin names can be found here https://github.com/romkatv/powerlevel10k#installation
zsh_plugin: zsh

# Setup p10k theme to use
# Valid values: lean, classic, rainbow, pure
p10k_prompt_style: "lean"

# Show current time
# Valid values: no, 24-hour, 12-hour
p10k_prompt_time: "24-hour"

# Prompt sperator
# Valid values: angled, vertical, slanted, round
p10k_prompt_separator: "angled"

# Prompt heads
# Valid values: sharp, blurred, slanted, round
p10k_prompt_head: "sharp"

# Prompt tails
# Valid values: flat, blurred, sharp, slanted, round
p10k_prompt_tails: flat

# Terminal prompt height
# Valid values: one-line, two-lines
p10k_prompt_height: two-lines

# Prompt connection, only used if "p10k_prompt_height" value is "two-lines"
# Valid values: disconnected, dotted, solid
p10k_prompt_connection: disconnected

# Prompt connection color, only used if
# "p10k_prompt_connection" value is "dotted" or "solid"
# or "p10k_prompt_frame" is not "no"
# Valid values: lightest, light, dark, darkest, black, white, green, blue
p10k_prompt_connection_color: "dark"

# Prompt frame connection
# Valid values: no, left, right, full
p10k_prompt_frame: left

# Sparse prompt with an empty line before promp
# Valid values: compact, sparse
p10k_prompt_spacing: compact

# Terminal flow
# Valid values: concise, fluent
p10k_prompt_flow: concise

# Enable transient prompt
# Valid values: yes, no
p10k_transient_prompt: "no"

nvm_version: "v0.40.3"
node_version: "22"
nvm_install_url: "https://raw.githubusercontent.com/nvm-sh/nvm"

starship:
  url: https://github.com/starship/starship/releases/download
  version: v1.23.0
  name: starship
  compiler: unknown-linux-musl
  extension: tar.gz

starship_darwin:
  url: https://github.com/starship/starship/releases/download
  version: v1.23.0
  name: starship
  compiler: aarch64-apple-darwin
  extension: tar.gz

nvim_darwin:
  nvim_url: https://github.com/neovim/neovim/releases/download
  nvim_version: v0.12.2
  nvim_name: nvim-macos-arm64
  nvim_extension: tar.gz

nvim_ubuntu_2404:
  nvim_url: https://github.com/neovim/neovim/releases/download
  nvim_version: v0.12.2
  nvim_name: nvim-linux-x86_64
  nvim_extension: tar.gz

nvim_ubuntu_2604:
  nvim_url: https://github.com/neovim/neovim/releases/download
  nvim_version: v0.12.2
  nvim_name: nvim-linux-x86_64
  nvim_extension: tar.gz

nvim_ubuntu_2004:
  nvim_url: https://github.com/neovim/neovim-releases/releases/download
  nvim_version: v0.12.2
  nvim_name: nvim-linux-x86_64
  nvim_extension: tar.gz

nvim_ubuntu_2004_arm64:
  nvim_url: https://github.com/neovim/neovim-releases/releases/download
  nvim_version: v0.12.2
  nvim_name: nvim-linux-arm64
  nvim_extension: tar.gz

nvim_ubuntu_2404_arm64:
  nvim_url: https://github.com/neovim/neovim/releases/download
  nvim_version: v0.12.2
  nvim_name: nvim-linux-arm64
  nvim_extension: tar.gz

fzy_source_package_url: "https://github.com/jhawthorn/fzy.git"
fzy_source_package_name: "fzy"
fzy_dest: "{{ ansible_facts['env'].HOME }}/fzy"
fzy_source_package_prefix: "{{ ansible_facts['env'].HOME }}/.local/bin"

luarock_url: https://github.com/luarocks/luarocks/releases/download
luarock_version: v3.12.2
luarock_name: linux-x86_64
luarock_file: luarocks
luarock_extension: zip

tarballs_config:
  fzf:
    url: https://github.com/junegunn/fzf/releases/download
    version: 0.65.1
    file_prefix: fzf
    extension: tar.gz
    architectures:
      x86_64:
          linux:
            os_suffix: linux
            arch_suffix: amd64
            extension: tar.gz
          darwin:
            os_suffix: darwin
            arch_suffix: amd64
            extension: "tar.gz"
      amd64:
        linux:
          os_suffix: linux
          arch_suffix: amd64
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: amd64
          extension: "tar.gz"
      arm64:
        linux:
          os_suffix: linux
          arch_suffix: arm64
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: arm64
          extension: "tar.gz"
      aarch64:
        linux:
          os_suffix: linux
          arch_suffix: arm64
          extension: tar.gz
          compiler: unknown-linux-gnu
  lazygit:
    url: https://github.com/jesseduffield/lazygit/releases/download
    version: 0.54.1
    file_prefix: lazygit
    extension: "tar.gz"
    architectures:
      x86_64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          extension: "tar.gz"
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: "tar.gz"
      amd64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          extension: "tar.gz"
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: "tar.gz"
      arm64:
        linux:
          os_suffix: Linux
          arch_suffix: arm64
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: arm64
          extension: "tar.gz"
      aarch64:
        linux:
          os_suffix: linux
          arch_suffix: arm64
          extension: tar.gz
          compiler: unknown-linux-gnu
  bat:
    url: https://github.com/sharkdp/bat/releases/download
    version: 0.25.0
    file_prefix: bat
    file_name: bat
    extension: tar.gz
    architectures:
      x86_64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          compiler: unknown-linux-gnu
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: tar.gz
          compiler: apple-darwin
      amd64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          compiler: unknown-linux-gnu
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: tar.gz
          compiler: apple-darwin
      arm64:
        linux:
          os_suffix: Linux
          arch_suffix: arm64
          extension: tar.gz
          compiler: unknown-linux-gnu
        darwin:
            os_suffix: darwin
            arch_suffix: aarch64
            extension: tar.gz
            compiler: apple-darwin
      aarch64:
        linux:
          os_suffix: linux
          arch_suffix: aarch64
          extension: tar.gz
          compiler: unknown-linux-gnu
  fd:
    url: https://github.com/sharkdp/fd/releases/download
    version: 10.2.0
    compiler: unknown-linux-gnu
    file_prefix: fd
    file_name: fd
    extension: tar.gz
    architectures:
      x86_64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          compiler: unknown-linux-gnu
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: tar.gz
          compiler: apple-darwin
      amd64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          compiler: unknown-linux-gnu
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: tar.gz
          compiler: apple-darwin
      arm64:
        linux:
          os_suffix: Linux
          arch_suffix: aarch64
          extension: tar.gz
          compiler: unknown-linux-gnu
        darwin:
            os_suffix: darwin
            arch_suffix: aarch64
            extension: tar.gz
            compiler: apple-darwin
      aarch64:
        linux:
          os_suffix: linux
          arch_suffix: aarch64
          extension: tar.gz
          compiler: unknown-linux-gnu
  btop:
    url: "https://github.com/aristocratos/btop/releases/download"
    file_prefix: btop
    file_name: btop
    version: "v1.4.7"
    extension: "tar.gz"
    architectures:
      x86_64:
        linux:
          arch_suffix: x86_64
          compiler: unknown-linux-musl
          extension: "tar.gz"
          os_suffix: Linux
      amd64:
        linux:
          arch_suffix: x86_64
          compiler: unknown-linux-musl
          extension: "tar.gz"
          os_suffix: Linux
      arm64:
        linux:
          arch_suffix: aarch64
          compiler: unknown-linux-musl
          extension: "tar.gz"
          os_suffix: Linux
        darwin:
          arch_suffix: aarch64
          compiler: unknown-linux-musl
          extension: "tar.gz"
          os_suffix: Linux
      aarch64:
        linux:
          arch_suffix: aarch64
          compiler: unknown-linux-musl
          extension: "tar.gz"
          os_suffix: Linux
  ripgrep:
    compiler: unknown-linux-gnu
    url: https://github.com/BurntSushi/ripgrep/releases/download
    version: 14.1.1
    file_prefix: rg
    file_name: ripgrep
    extension: tar.gz
    architectures:
      x86_64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          compiler: unknown-linux-musl
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: tar.gz
          compiler: apple-darwin
      amd64:
        linux:
          os_suffix: Linux
          arch_suffix: x86_64
          compiler: unknown-linux-musl
          extension: tar.gz
        darwin:
          os_suffix: darwin
          arch_suffix: x86_64
          extension: tar.gz
          compiler: apple-darwin
      arm64:
        linux:
          os_suffix: Linux
          arch_suffix: aarch64
          extension: tar.gz
          compiler: unknown-linux-gnu
        darwin:
            os_suffix: darwin
            arch_suffix: aarch64
            extension: tar.gz
            compiler: apple-darwin
      aarch64:
        linux:
          os_suffix: linux
          arch_suffix: aarch64
          extension: tar.gz
          compiler: unknown-linux-gnu
  eza:
    url: https://github.com/eza-community/eza/releases/download
    version: 0.23.4
    file_prefix: eza
    extension: zip
    architectures:
      x86_64:
        linux:
          arch_suffix: x86_64
          compiler: unknown-linux-musl
          extension: zip
      amd64:
        linux:
          arch_suffix: x86_64
          compiler: unknown-linux-musl
          extension: zip
      arm64:
        linux:
          arch_suffix: aarch64
          compiler: unknown-linux-gnu
          extension: zip
      aarch64:
        linux:
          arch_suffix: aarch64
          compiler: unknown-linux-gnu
          extension: zip

# Installation directory
install_dir: "{{ ansible_facts['env'].HOME }}/.local/bin"
temp_dir: "{{ ansible_facts['env'].HOME }}/myapp"
